Protect an ABI_CONTIGUOUS pointer causing issue on some GCC flavors
An error occurs on testfarm buda specifically (GCC 8.2):

m_hamiltonian.F90:1030:16:

    ham%kg_k  => kg_k
                1
Error: Assignment to contiguous pointer from non-contiguous target at (1)

Former-commit-id: 7054edae00f58df87cccbdc3729e5389f21857bb