Protect an ABI_CONTIGUOUS pointer causing issue on some GCC flavors
An error occurs on testfarm buda specifically (GCC 8.2):

m_hamiltonian.F90:1030:16:

    ham%kg_k  => kg_k
                1
Error: Assignment to contiguous pointer from non-contiguous target at (1)

Former-commit-id: cf5c318beb1d2f8e21a76e3dceda0fcaddf29cad